Vagrant.configure("2") do |config|

  config.vm.box = "generic/alma9"
  config.vm.box_version = "4.3.12"

  (1..3).each do |i|
    config.vm.define "web-#{i}" do |web|
      web.vm.hostname = "web-#{i}"

      web.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 1024
      end

      web.vm.network "private_network", ip: "192.168.56.10#{i}"

      web.vm.network "forwarded_port", guest: 80, host: 8080 + i - 1

      web.vm.provision "shell", inline: <<-SHELL
        echo "Updating package list..."
        sudo dnf update -y
        
        echo "Installing Nginx..."
        sudo dnf install -y nginx
        
        echo "Enabling and starting Nginx service..."
        sudo systemctl enable --now nginx
        
        echo "Provisioning for web_#{i} complete."
      SHELL
    end
  end
end